import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
          >
            <div className="flex flex-col text-xl gap-6 px-10 pt-5">
            <Link href={"/pokemon"} className="hover:text-red-500">=Back</Link>
            <Link href={"/"} className="hover:text-green-500">=hOME</Link>
            </div>
        {children}

      </ThemeProvider>
      </body> 
    </html>
  );
}
